name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master 
  release:
    types:
      - published

env:
  CIBW_TEST_REQUIRES: pytest 
  CIBW_TEST_COMMAND: pytest {project}/tests

jobs:
          
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.11.2

      - name: Symlink g++-4.2 on MacOS
        if: runner.os == 'macOS'
        run: |
          ln -s /usr/bin/g++ /usr/local/bin/g++-4.2

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          #CIBW_BEFORE_ALL_LINUX: pip install cmake && ln -s $(which cmake) /usr/local/bin/cmake
          CIBW_BEFORE_ALL_MACOS: brew install --cask xquartz 
          CIBW_BEFORE_BUILD: pip install -r requirements.txt && python install_conan_packages.py
          CIBW_SKIP: pp* *-win32 *-musllinux_* *-manylinux_i686 *aarch64 *ppc64* *s390*

      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
      
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.12'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

  coverage:
    name: Run coverage analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          python install_conan_packages.py
          pip install -e .
      
      - name: Run coverage test
        run:  pytest --cov-report term-missing --cov-report xml:coverage.xml --cov pycimg tests/

      - name: Upload codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
